force-app/main/default/objects/Batch__c/Batch__c.object-meta.xml
<CustomObject>
    <label>Batch</label>
    <nameField>
        <label>Batch Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Batches</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Batch__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <label>Course</label>
    <referenceTo>Course__c</referenceTo>
    <relationshipLabel>Batch</relationshipLabel>
    <relationshipName>Batch</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Course__c/Course__c.object-meta.xml
<CustomObject>
    <label>Course</label>
    <nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Course__c/fields/Course_Code__c.field-meta.xml
<CustomField>
    <fullName>Course_Code__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Course Code can only be a maximum of six characters including special characters(*@#$%,-)</inlineHelpText>
    <label>Course Code</label>
    <length>150</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/BatchObjectApiControllerTest.cls
@isTest
private class BatchObjectApiControllerTest {

    @isTest
    static void testGetBatchRecords() {
      
        Course__c testCourses = new Course__c();
        
           testCourses.Name = 'TestCourse1';
           testCourses.Course_Code__c = '12345';
        
        insert testCourses;

        
        List<Batch__c> testRecords = new List<Batch__c>();
        for (Integer i = 0; i < 5; i++) {
            testRecords.add(new Batch__c(Name='Test Batch ' + i, Course__c = testCourses.Id));
        }
        insert testRecords;

        
        Test.startTest();
        List<Batch__c> result = BatchObjectApiController.GetBatchRecords();
        Test.stopTest();

        
       
        
    }
}