force-app/main/default/objects/Batch__c/Batch__c.object-meta.xml
<CustomObject>
    <label>Batch</label>
    <nameField>
        <label>Batch Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Batches</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Batch__c/fields/Batch_AutoNum__c.field-meta.xml
<CustomField>
    <fullName>Batch_AutoNum__c</fullName>
    <displayFormat>B-{000}</displayFormat>
    <label>Batch AutoNum</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Batch__c/fields/Batch_Description__c.field-meta.xml
<CustomField>
    <fullName>Batch_Description__c</fullName>
    <label>Batch Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Batch__c/fields/Batch_Month__c.field-meta.xml
<CustomField>
    <fullName>Batch_Month__c</fullName>
    <label>Batch Month</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Quarter__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>April</fullName>
            </value>
            <value>
                <fullName>May</fullName>
            </value>
            <value>
                <fullName>June</fullName>
            </value>
            <value>
                <fullName>July</fullName>
            </value>
            <value>
                <fullName>August</fullName>
            </value>
            <value>
                <fullName>September</fullName>
            </value>
            <value>
                <fullName>October</fullName>
            </value>
            <value>
                <fullName>November</fullName>
            </value>
            <value>
                <fullName>December</fullName>
            </value>
            <value>
                <fullName>January</fullName>
            </value>
            <value>
                <fullName>February</fullName>
            </value>
            <value>
                <fullName>March</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Batch__c/fields/Batch_Timing__c.field-meta.xml
<CustomField>
    <fullName>Batch_Timing__c</fullName>
    <label>Batch Timing</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Weekends Morning-WEM</fullName>
            </value>
            <value>
                <fullName>Weekends Evening-WEE</fullName>
            </value>
            <value>
                <fullName>Weekdays Morning-WDM</fullName>
            </value>
            <value>
                <fullName>Weekdays Evening-WDE</fullName>
            </value>
            <value>
                <fullName>Weekends Full Day-WEF</fullName>
            </value>
            <value>
                <fullName>Weekdays Full Day-WDF</fullName>
            </value>
            <value>
                <fullName>Self-Paced</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Batch__c/fields/Batch_Type__c.field-meta.xml
<CustomField>
    <fullName>Batch_Type__c</fullName>
    <label>Batch Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Inperson</fullName>
            </value>
            <value>
                <fullName>Virtual</fullName>
            </value>
            <value>
                <fullName>Corporate</fullName>
            </value>
            <value>
                <fullName>Self-Paced</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Batch__c/fields/Training_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Training_End_Date__c</fullName>
    <label>Training End Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Batch__c/fields/Training_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Training_Start_Date__c</fullName>
    <label>Training Start Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Batch__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <label>Year</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>2011-2012</fullName>
            </value>
            <value>
                <fullName>2012-2013</fullName>
            </value>
            <value>
                <fullName>2013-2014</fullName>
            </value>
            <value>
                <fullName>2014-2015</fullName>
            </value>
            <value>
                <fullName>2015-2016</fullName>
            </value>
            <value>
                <fullName>2016-2017</fullName>
            </value>
            <value>
                <fullName>2017-2018</fullName>
            </value>
            <value>
                <fullName>2018-2019</fullName>
            </value>
            <value>
                <fullName>2019-2020</fullName>
            </value>
            <value>
                <fullName>2020-2021</fullName>
            </value>
            <value>
                <fullName>2021-2022</fullName>
            </value>
            <value>
                <fullName>2022-2023</fullName>
            </value>
            <value>
                <fullName>2023-2024</fullName>
            </value>
            <value>
                <fullName>2024-2025</fullName>
            </value>
            <value>
                <fullName>2025-2026</fullName>
            </value>
            <value>
                <fullName>2026-2027</fullName>
            </value>
            <value>
                <fullName>2027-2028</fullName>
            </value>
            <value>
                <fullName>2028-2029</fullName>
            </value>
            <value>
                <fullName>2029-2030</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BatchObjectApiController.cls
@RestResource(urlMapping='/BatchAPIrecords/*')
global with sharing class BatchObjectApiController {
    @HttpGet
    global static List<Batch__c> GetBatchRecords() {
            List<Batch__c>  records;
              records=  [SELECT Id, Name, Course_Name__c,Batch_AutoNum__c,Quarter__c,Training_Start_Date__c, 
              Training_End_Date__c,Year__c,Batch_Type__c,Batch_Month__c,Batch_Timing__c,Batch_Description__c FROM Batch__c 
              Where Publish__c = true ];
         //RestResponse res = RestContext.response;
 	//res.responseBody = Blob.valueOf(JSON.serialize(records));
 	//Blob b = Blob.valueOf(JSON.serialize(records));
        return records;
    }
}