force-app/main/default/objects/Account_Payment_Information__c/Account_Payment_Information__c.object-meta.xml
<CustomObject>
    <label>Account Payment Information</label>
    <nameField>
        <displayFormat>ICAPI-{00000}</displayFormat>
        <label>Account Payment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Payment Information</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Payment_Information__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Will be auto-filled based on the Opportunity.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Payment Information</relationshipLabel>
    <relationshipName>Account_Payment_Information</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Payment_Information__c/fields/Batch__c.field-meta.xml
<CustomField>
    <fullName>Batch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Will be auto-filled based on the Opportunity.</inlineHelpText>
    <label>Batch</label>
    <referenceTo>Batch__c</referenceTo>
    <relationshipLabel>Account Payment Information</relationshipLabel>
    <relationshipName>Account_Payment_Information</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Payment_Information__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Will be auto-filled based on the Opportunity.</inlineHelpText>
    <label>Course</label>
    <referenceTo>Course__c</referenceTo>
    <relationshipLabel>Account Payment Information</relationshipLabel>
    <relationshipName>Account_Payment_Information</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Payment_Information__c/fields/Next_Payment_Date__c.field-meta.xml
<CustomField>
    <fullName>Next_Payment_Date__c</fullName>
    <inlineHelpText>If status is Partially Received, then the Next Payment Status field is mandatory.</inlineHelpText>
    <label>Next Payment Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account_Payment_Information__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Account Payment Information</relationshipLabel>
    <relationshipName>Account_Payment_Information</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Training_Information__c/Account_Training_Information__c.object-meta.xml
<CustomObject>
    <label>Account Training Information</label>
    <nameField>
        <displayFormat>ICATI--{00000}</displayFormat>
        <label>Account Training Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Training Information</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Training_Information__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Training Information</relationshipLabel>
    <relationshipName>Account_Training_Information</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Training_Information__c/fields/Account_Payment_Information__c.field-meta.xml
<CustomField>
    <fullName>Account_Payment_Information__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Payment Information</label>
    <referenceTo>Account_Payment_Information__c</referenceTo>
    <relationshipLabel>Account Training Information</relationshipLabel>
    <relationshipName>Account_Training_Information</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Training_Information__c/fields/Batch__c.field-meta.xml
<CustomField>
    <fullName>Batch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Batch</label>
    <referenceTo>Batch__c</referenceTo>
    <relationshipLabel>Account Training Information</relationshipLabel>
    <relationshipName>Account_Training_Information</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Training_Information__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Course</label>
    <referenceTo>Course__c</referenceTo>
    <relationshipLabel>Account Training Information</relationshipLabel>
    <relationshipName>Account_Training_Information</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Batch__c/Batch__c.object-meta.xml
<CustomObject>
    <label>Batch</label>
    <nameField>
        <label>Batch Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Batches</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Batch__c/fields/Batch_Month__c.field-meta.xml
<CustomField>
    <fullName>Batch_Month__c</fullName>
    <label>Batch Month</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Quarter__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>April</fullName>
            </value>
            <value>
                <fullName>May</fullName>
            </value>
            <value>
                <fullName>June</fullName>
            </value>
            <value>
                <fullName>July</fullName>
            </value>
            <value>
                <fullName>August</fullName>
            </value>
            <value>
                <fullName>September</fullName>
            </value>
            <value>
                <fullName>October</fullName>
            </value>
            <value>
                <fullName>November</fullName>
            </value>
            <value>
                <fullName>December</fullName>
            </value>
            <value>
                <fullName>January</fullName>
            </value>
            <value>
                <fullName>February</fullName>
            </value>
            <value>
                <fullName>March</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Batch__c/fields/Batch_Timing__c.field-meta.xml
<CustomField>
    <fullName>Batch_Timing__c</fullName>
    <label>Batch Timing</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Weekends Morning-WEM</fullName>
            </value>
            <value>
                <fullName>Weekends Evening-WEE</fullName>
            </value>
            <value>
                <fullName>Weekdays Morning-WDM</fullName>
            </value>
            <value>
                <fullName>Weekdays Evening-WDE</fullName>
            </value>
            <value>
                <fullName>Weekends Full Day-WEF</fullName>
            </value>
            <value>
                <fullName>Weekdays Full Day-WDF</fullName>
            </value>
            <value>
                <fullName>Self-Paced</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Batch__c/fields/Batch_Type__c.field-meta.xml
<CustomField>
    <fullName>Batch_Type__c</fullName>
    <label>Batch Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Inperson</fullName>
            </value>
            <value>
                <fullName>Virtual</fullName>
            </value>
            <value>
                <fullName>Corporate</fullName>
            </value>
            <value>
                <fullName>Self-Paced</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Batch__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <label>Course</label>
    <referenceTo>Course__c</referenceTo>
    <relationshipLabel>Batch</relationshipLabel>
    <relationshipName>Batch</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Batch__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <label>Year</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>2011-2012</fullName>
            </value>
            <value>
                <fullName>2012-2013</fullName>
            </value>
            <value>
                <fullName>2013-2014</fullName>
            </value>
            <value>
                <fullName>2014-2015</fullName>
            </value>
            <value>
                <fullName>2015-2016</fullName>
            </value>
            <value>
                <fullName>2016-2017</fullName>
            </value>
            <value>
                <fullName>2017-2018</fullName>
            </value>
            <value>
                <fullName>2018-2019</fullName>
            </value>
            <value>
                <fullName>2019-2020</fullName>
            </value>
            <value>
                <fullName>2020-2021</fullName>
            </value>
            <value>
                <fullName>2021-2022</fullName>
            </value>
            <value>
                <fullName>2022-2023</fullName>
            </value>
            <value>
                <fullName>2023-2024</fullName>
            </value>
            <value>
                <fullName>2024-2025</fullName>
            </value>
            <value>
                <fullName>2025-2026</fullName>
            </value>
            <value>
                <fullName>2026-2027</fullName>
            </value>
            <value>
                <fullName>2027-2028</fullName>
            </value>
            <value>
                <fullName>2028-2029</fullName>
            </value>
            <value>
                <fullName>2029-2030</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Course__c/Course__c.object-meta.xml
<CustomObject>
    <label>Course</label>
    <nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Course__c/fields/Course_Code__c.field-meta.xml
<CustomField>
    <fullName>Course_Code__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Course Code can only be a maximum of six characters including special characters(*@#$%,-)</inlineHelpText>
    <label>Course Code</label>
    <length>150</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/ICForceUtilityTest.cls
@isTest
public class ICForceUtilityTest {
    @isTest static void upsertRecords(){
        Account acct= new Account(Name='Test Account');
        insert acct;
        Course__c course=new Course__c(Name='Test Course',Course_Code__c='TEST');
        insert course;
        Course__c course2=new Course__c(Name='Test Course2',Course_Code__c='TEST2');
        insert course2;
        Course__c course3=new Course__c(Name='Test Course3',Course_Code__c='TEST3');
        insert course3;
        Course__c course4=new Course__c(Name='Test Course4',Course_Code__c='TEST4');
        insert course4;
        Batch__c batch= new Batch__c(Course__c=course.id,Quarter__c='Q1',Batch_Month__c ='April',Batch_Type__c='Virtual',Year__c='2023-2024',Batch_Timing__c='Weekends Morning-WEM');
        insert batch;
        Batch__c batch2= new Batch__c(Course__c=course2.id,Quarter__c='Q4',Batch_Month__c ='March',Batch_Type__c='Virtual',Year__c='2023-2024',Batch_Timing__c='Weekends Morning-WEM');
        insert batch2;
        Batch__c batch3= new Batch__c(Course__c=course3.id,Quarter__c='Q1',Batch_Month__c ='April',Batch_Type__c='Virtual',Year__c='2023-2024',Batch_Timing__c='Weekends Morning-WEM');
        insert batch3;
        Batch__c batch4= new Batch__c(Course__c=course4.id,Quarter__c='Q4',Batch_Month__c ='March',Batch_Type__c='Virtual',Year__c='2023-2024',Batch_Timing__c='Weekends Morning-WEM');
        insert batch4;
        Opportunity oppty = new Opportunity(Name=acct.Name + ' Opportunity',StageName='Prospecting',CloseDate=System.today().addMonths(1),AccountId=acct.Id,Batch__c= batch.Id,Course__c=course.id);
        insert oppty;
        Opportunity oppty2 = new Opportunity(Name=acct.Name + ' Opportunity2',StageName='Prospecting',CloseDate=System.today().addMonths(1),AccountId=acct.Id,Batch__c= batch2.Id,Course__c=course2.id);
        insert oppty2;
        Opportunity oppty3 = new Opportunity(Name=acct.Name + ' Opportunity3',StageName='Prospecting',CloseDate=System.today().addMonths(1),AccountId=acct.Id,Batch__c= batch3.Id,Course__c=course3.id);
        insert oppty3;
        Account_Payment_Information__c api = new Account_Payment_Information__c(Account__c=acct.Id,Batch__c= batch.Id,Course__c=course.id,Opportunity__c=oppty.Id);
        insert api;
        Account_Payment_Information__c api2 = new Account_Payment_Information__c(Account__c=acct.Id,Batch__c= batch2.Id,Course__c=course2.id,Opportunity__c=oppty2.Id,Next_Payment_Date__c=System.today().addMonths(2));
        insert api2;
        Account_Training_Information__c ati = new Account_Training_Information__c(Account__c=acct.Id,Batch__c= batch.Id,Course__c=course.id);
        insert ati;
        Account_Training_Information__c ati2 = new Account_Training_Information__c(Account__c=acct.Id,Batch__c= batch2.Id,Course__c=course2.id);
        insert ati2;
        
        Test.startTest();
        
        ICForceUtility.upsertOppty(oppty);
        oppty2.Batch__c=batch2.Id;
        oppty2.Course__c=course2.Id;
        ICForceUtility.upsertOppty(oppty2);
        
        
        ICForceUtility.upsertAPI(api);
        api2.Batch__c=batch2.Id;
        api2.Course__c=course2.Id;
        ICForceUtility.upsertAPI(api2);
        ICForceUtility.deleteOppty(oppty2);
        delete oppty3;
        
        ICForceUtility.upsertATI(ati);
        ati2.Batch__c=batch2.Id;
        ati2.Course__c=course2.Id;
        ICForceUtility.upsertATI(ati2);
        
        List<Batch__c> batchTestLSt= new List<Batch__c>();
        batchTestLSt.add(batch);
        ICForceUtility.deleteBatch(batchTestLSt);
        
        List<Course__c> courseTestLSt= new List<Course__c>();
        courseTestLSt.add(course);
        ICForceUtility.deleteCourse(courseTestLSt);
        
        api.Next_Payment_Date__c=System.today().addMonths(6);
        ICForceUtility.upsertAPI(api);
       // List<Account_Payment_Information__c> apiLst=new List<Account_Payment_Information__c>();
      //  apiLst.add(api);
        ICForceUtility.upsertAPI(api);
        
        delete batch3;
        delete batch4;
        delete course4;
        
        Test.stopTest();
        
    }
}